name: angular_dart_example
version: 0.0.1
dependencies:
  angular:
    path: ../
  browser: any
  unittest: any

transformers:
- angular:
    dart_entries:
    - web/todo.dart
    - web/bouncing_balls.dart
    html_files: # Need to split out to per-entry assets
    - web/todo.html
    - web/bouncing_balls.html

dependency_overrides:
  di:
    git: https://github.com/angular/di.dart.git
